# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

def podEquals
  pod 'Alamofire', '~> 5.4'
  pod 'SwiftLint'
  # used this repo to fix PrivacyInfo issue, in the future check if this issues is resolved to return to the official pod
  pod 'SVProgressHUD', :git => 'https://github.com/mitsuke2020/SVProgressHUD', :commit => 'b3ccdd5f66592470f034c053752450a5254b965e'
  pod 'RKDropdownAlert'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'LZViewPager', '~> 1.0.4'
  pod 'OneSignal', '>= 5.0.0', '< 6.0'
  pod 'Pulsator'
  pod 'CVCalendar', '~> 1.6.2'
  pod 'MJPEGStreamLib'
  pod 'Kingfisher', '~> 5.14'
  pod 'GoogleMLKit/FaceDetection', '2.3.0'
  pod 'CountryPickerView'
  pod 'PhoneNumberKit', '~> 3.3'
  pod 'SideMenu'
end

target 'ReproducerApp' do
  use_frameworks! :linkage => :static
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  podEquals

  target 'ReproducerAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer_representation|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer_representation,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer_representation.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
              config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
              config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_REMOTE_PROFILE=0'
          end
    end
  end
end
